#! /usr/bin/env python
"""
Launches Free Look Control without ActionServer.

If ActionServer is needed, use flc_as instead.
"""
import flc_teleoperation.flc_control

if __name__ == '__main__':
    flc_teleoperation.flc_control.main()
